

version: '3'
services:
  django:
    build: .
    depends_on:
      - db
    volumes:
      - static_volume:/static
    restart: unless-stopped
  db:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=storage
      - POSTGRES_PASSWORD=storage
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
  nginx:
    image: nginx:latest
    depends_on:
      - django
    volumes:
      - static_volume:/static
      - ./docker/nginx_default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  static_volume: