

version: '3'
services:
  django:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./app_storage:/persistence/do-backup
    restart: unless-stopped
  db:
    image: postgres:12.9
    environment:
      - POSTGRES_DB=storage
      - POSTGRES_USER=storage
      - POSTGRES_PASSWORD=storage
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw

volumes:
  postgres_data: